Fixed undefined reference to File_Wtv
Fixed undefined reference to File_Wtv, which is caused by using `MEDIAINFO_WM_YES` instead of `MEDIAINFO_WTV_YES`